export enum ChatSocketEvent {
    JoinChat = 'joinChat',
    JoinGameChat = 'joinGameChat',
    PostMessage = 'postChatMessage',
    GetMessage = 'getChatMessage',
    UserLeft = 'userLeftChat',
    LeaveChat = 'leaveChat',
    BanUser = 'banChatUser',
    OnUserBanned = 'onChatUserBanned',
    UpdateUsername = 'updateChatUsername',
    JoinChats = 'joinChats',
    OnChatJoined = 'onChatJoined',
    InitializeChats = 'initializeChats',
    RemoveChat = 'removeChat',
    CreateChat = 'createChat',
    OnChatCreated = 'onChatCreated',
    OnNonUserChats = 'onNonUserChats',
    GetNonUserChats = 'getNonUserChats',
    DeleteChat = 'deleteChat',
    OnChatDeleted = 'onChatDeleted',
    ChatExists = 'chatExists',
    NotFriendError = 'notFriendError',
    CleanupFriendOnlyChats = 'cleanupFriendOnlyChats',
    UpdateUserChats = 'updateUserChats',
    ResetUserNotifications = 'resetUserNotifications',
    GetUserNotifications = 'getUserNotifications',
}
